name: Terraform CI

on:
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-ci.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform fmt
        run: cd terraform && terraform fmt -check || true

      - name: Terraform Init
        run: cd terraform && terraform init -backend=false

      - name: Terraform Plan
        run: cd terraform && terraform plan -var="project_prefix=triggerforge" -out=tfplan || true
